package fr.univartois.butinfo.sae.abyss.explore.model;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents a Page entity stored in the MongoDB database.
 * Each Page has a unique identifier, a name, tags, associated posts, and a creation timestamp.
 */
@Document(collection = "Pages")
public class Page {

    /**
     * Unique identifier for the Page, automatically generated by MongoDB.
     */
    @Id
    private ObjectId id;

    /**
     * The name or title of the Page.
     */
    private String name;

    /**
     * An array of tags associated with the Page.
     */
    private String[] tags;

    /**
     * An array of ObjectIds representing the posts linked to this Page.
     */
    private ObjectId[] posts;

    /**
     * The timestamp indicating when the Page was created.
     */
    private LocalDateTime createdAt;

    /**
     * Constructor to create a Page with a name.
     * The creation timestamp is automatically set to the current time.
     *
     * @param name The name of the Page.
     */
    public Page(String name) {
        this.name = name;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructor to create a Page with a name and tags.
     * The creation timestamp is automatically set to the current time.
     *
     * @param name The name of the Page.
     * @param tags The tags associated with the Page.
     */
    public Page(String name, String[] tags) {
        this.name = name;
        this.tags = tags;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Gets the unique identifier of the Page.
     *
     * @return The ObjectId of the Page.
     */
    public ObjectId getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Page.
     *
     * @param id The ObjectId to set.
     */
    public void setId(ObjectId id) {
        this.id = id;
    }

    /**
     * Gets the name of the Page.
     *
     * @return The name of the Page.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the Page.
     *
     * @param name The name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the tags associated with the Page.
     *
     * @return An array of tags.
     */
    public String[] getTags() {
        return tags;
    }

    /**
     * Sets the tags associated with the Page.
     *
     * @param tags The tags to set.
     */
    public void setTags(String[] tags) {
        this.tags = tags;
    }

    /**
     * Gets the posts linked to the Page.
     *
     * @return An array of ObjectIds representing the posts.
     */
    public ObjectId[] getPosts() {
        return posts;
    }

    /**
     * Sets the posts linked to the Page.
     *
     * @param posts The posts to set.
     */
    public void setPosts(ObjectId[] posts) {
        this.posts = posts;
    }

    /**
     * Gets the creation timestamp of the Page.
     *
     * @return The creation timestamp.
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp of the Page.
     *
     * @param createdAt The timestamp to set.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}