// java
package fr.univartois.butinfo.sae.abyss.social.model;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents a Group entity stored in the MongoDB collection "Groups".
 * This class is annotated with Spring Data MongoDB annotations to map
 * the fields to the database structure.
 */
@Document(collection = "Groups")
public class Groups {

    /**
     * The unique identifier for the group, automatically generated by MongoDB.
     */
    @Id
    private ObjectId id;

    /**
     * The name of the group.
     */
    @NotNull
    private String name;

    /**
     * Tags associated with the group.
     */
    private List<String> tags;

    /**
     * A list of ObjectIds referencing posts belonging to the group.
     */
    private List<ObjectId> posts;

    /**
     * The date and time when the group was created.
     * Mapped to the database field `created_at`.
     */
    @Field("created_at")
    private LocalDateTime createdAt;

    /**
     * Constructs a new Group with empty lists and current creation time.
     */
    public Groups() {
        this.tags = new ArrayList<>();
        this.posts = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new Group with the specified name.
     *
     * @param name The name of the group.
     */
    public Groups(@NotNull String name) {
        this.name = name;
        this.tags = new ArrayList<>();
        this.posts = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new Group with the specified name and tags.
     *
     * @param name The name of the group.
     * @param tags The tags to initialize.
     */
    public Groups(@NotNull String name, List<String> tags) {
        this.name = name;
        this.tags = tags != null ? tags : new ArrayList<>();
        this.posts = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags != null ? tags : new ArrayList<>();
    }

    public List<ObjectId> getPosts() {
        return posts;
    }

    public void setPosts(List<ObjectId> posts) {
        this.posts = posts != null ? posts : new ArrayList<>();
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Groups)) return false;
        Groups groups = (Groups) o;
        return Objects.equals(id, groups.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "Groups{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", tags=" + tags +
                ", posts=" + posts +
                ", createdAt=" + createdAt +
                '}';
    }
}
