package fr.univartois.butinfo.sae.abyss.social.model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.Arrays;

@Document(collection = "Posts")
/**
 * MongoDB document representing a social post.
 */
public class Post {
    /** Unique identifier generated by MongoDB. */
    @Id
    private ObjectId id;

    /** Identifier of the user who created the post. */
    @NotNull
    @Field("user_id")
    private ObjectId userId;

    /** Main textual content of the post. */
    @NotBlank
    private String content;

    /** Identifiers of comments attached to this post. */
    @NotNull
    private ObjectId[] comments = new ObjectId[0];

    /** Number of likes, always non-negative. */
    @Min(0)
    private int like = 0;

    /** Number of dislikes, always non-negative. */
    @Min(0)
    private int dislike = 0;

    /** Timestamp of post creation. */
    @Field("created_at")
    private LocalDateTime createdAt;

    /** Default constructor required by Spring Data. */
    public Post() {

    }

    /**
     * Builds a post with an author and content.
     *
     * @param userId  identifier of the author
     * @param content text content of the post
     */
    public Post(ObjectId userId, String content) {
        this.userId = userId;
        this.content = content;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * @return the MongoDB identifier of this post
     */
    public ObjectId getId() {
        return id;
    }

    /**
     * @return the identifier of the author
     */
    public ObjectId getUserId() {
        return userId;
    }

    /**
     * Sets the identifier of the author.
     *
     * @param userId author identifier
     */
    public void setUserId(ObjectId userId) {
        this.userId = userId;
    }

    /**
     * @return the textual content of the post
     */
    public String getContent() {
        return content;
    }

    /**
     * Updates the post content.
     *
     * @param content new text content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * @return comment identifiers linked to this post
     */
    public ObjectId[] getComments() {
        return comments;
    }

    /**
     * Replaces the comment identifier list.
     * If {@code comments} is {@code null}, an empty array is stored instead.
     *
     * @param comments new comment identifier array
     */
    public void setComments(ObjectId[] comments) {
        this.comments = comments == null ? new ObjectId[0] : comments;
    }

    /**
     * @return current like count
     */
    public int getLike() {
        return like;
    }

    /**
     * Sets the like count, clamped to a non-negative value.
     *
     * @param like new like count
     */
    public void setLike(int like) {
        this.like = Math.max(0, like);
    }

    /**
     * @return current dislike count
     */
    public int getDislike() {
        return dislike;
    }

    /**
     * Sets the dislike count, clamped to a non-negative value.
     *
     * @param dislike new dislike count
     */
    public void setDislike(int dislike) {
        this.dislike = Math.max(0, dislike);
    }

    /**
     * @return creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Updates the creation timestamp.
     *
     * @param createdAt creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Appends a comment identifier to the current list.
     * Ignores {@code null} identifiers.
     *
     * @param commentId identifier of the comment to add
     */
    public void addComment(ObjectId commentId) {
        if (commentId == null) {
            return;
        }

        int nextIndex = comments.length;
        comments = Arrays.copyOf(comments, nextIndex + 1);
        comments[nextIndex] = commentId;
    }

    /** Increments the like counter by one. */
    public void incrementLike() {
        like++;
    }

    /** Increments the dislike counter by one. */
    public void incrementDislike() {
        dislike++;
    }

}
