package fr.univartois.butinfo.sae.abyss.social.model;

import org.bson.types.Binary;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * MongoDB document representing a social post.
 */

@Document(collection = "Posts")

public class Post {
    /** Unique identifier generated by MongoDB. */
    @Id
    private ObjectId id;

    /** User who creates the post */
    @DBRef
    private User user;

    /** Main textual content of the post. */
    private String content;

    /** Image of the post */
    private Binary image;

    /** Identifiers of comments attached to this post. */
    private ObjectId[] comments = new ObjectId[0];

    /** Users who liked this post. */
    @DBRef
    private List<User> likes = new ArrayList<>();

    /** Users who disliked this post. */
    @DBRef
    private List<User> dislikes = new ArrayList<>();

    /** Timestamp of post creation. */
    @Field("created_at")
    private LocalDateTime createdAt;

    /** Default constructor required by Spring Data. */
    public Post() {

    }

    /**
     * Builds a post with an author and content.
     *
     * @param user  The author
     */
    public Post(User user) {
        this.user = user;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * @return the MongoDB identifier of this post
     */
    public ObjectId getId() {
        return id;
    }

    /**
     * @return the author
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the author.
     *
     * @param user author
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the textual content of the post
     */
    public String getContent() {
        return content;
    }

    /**
     * Updates the post content.
     *
     * @param content new text content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * @return the image of the post
     */

    public Binary getImage() {
        return image;
    }

    /**
     * Updates the post image.
     *
     * @param image new image
     */
    public void setImage(Binary image) {}

    /**
     * @return comment identifiers linked to this post
     */
    public ObjectId[] getComments() {
        return comments;
    }

    /**
     * Replaces the comment identifier list.
     * If {@code comments} is {@code null}, an empty array is stored instead.
     *
     * @param comments new comment identifier array
     */
    public void setComments(ObjectId[] comments) {
        this.comments = comments == null ? new ObjectId[0] : comments;
    }

    /**
     * @return current users who like this post
     */
    public List<User> getLikes() {
        return likes;
    }

    /**
     * @return current like counter
     */
    public int getNumbersOfLikes() {
        return likes.size();
    }

    /**
     * @return current users who dislike this post
     */
    public List<User> getDislikes() {
        return dislikes;
    }

    /**
     * @return current dislike counter
     */
    public int getNumbersOfDislikes() {
        return dislikes.size();
    }



    /**
     * Sets the like tab
     *
     * @param likes new like tab
     */
    public void setLikes(List<User> likes) {
        if (likes == null) {
            this.likes = new ArrayList<>();
        } else {
            this.likes = likes;
        }
    }

    /**
     * Sets the dislike tab
     *
     * @param dislikes new dislike tab
     */
    public void setDislikes(List<User> dislikes) {
        if (dislikes == null) {
            this.dislikes = new ArrayList<>();
        } else {
            this.dislikes = dislikes;
        }
    }

    /**
     * @return creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Updates the creation timestamp.
     *
     * @param createdAt creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Appends a comment identifier to the current list.
     * Ignores {@code null} identifiers.
     *
     * @param commentId identifier of the comment to add
     */
    public void addComment(ObjectId commentId) {
        if (commentId == null) {
            return;
        }

        int nextIndex = comments.length;
        comments = Arrays.copyOf(comments, nextIndex + 1);
        comments[nextIndex] = commentId;
    }


}
