package fr.univartois.butinfo.sae.abyss.social.model;

import org.bson.types.Binary;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a User entity stored in the MongoDB collection "Users".
 * This class is annotated with Spring Data MongoDB annotations to map
 * the fields to the database structure.
 */
@Document(collection = "Users")
public class User {

    /**
     * The unique identifier for the user, automatically generated by MongoDB.
     */
    @Id
    private ObjectId id;

    /**
     * The username of the user.
     */
    private String username;

    /**
     * The email address of the user.
     */
    private String email;

    /**
     * The role of the user, represented by the ROLES enum.
     */
    private ROLES role;

    /**
     * The profile picture of the user, stored as binary data.
     */
    private Binary profilePicture;

    /**
     * A list of ObjectIds representing the user's friends.
     */
    private List<ObjectId> friends;

    /**
     * A list of ObjectIds representing the users banned by this user.
     */
    private List<ObjectId> usersBanned;

    /**
     * A list of ObjectIds representing the groups the user is part of.
     */
    private List<ObjectId> groups;

    /**
     * A list of ObjectIds representing the pages the user is associated with.
     */
    private List<ObjectId> pages;

    /**
     * The date and time when the user was created.
     */
    private LocalDateTime createdAt;

    public User(){

    }

    /**
     * Constructs a new User with the specified username.
     *
     * @param username The username of the user.
     */
    public User(String username, String email) {
        this.username = username;
        this.email = email;
        this.role = ROLES.USER;
        this.profilePicture = null;
        this.friends = new ArrayList<>();
        this.usersBanned = new ArrayList<>();
        this.groups = new ArrayList<>();
        this.pages = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new User with the specified username, email, and role.
     *
     * @param username The username of the user.
     * @param email The email address of the user.
     * @param role The role of the user.
     */
    public User(String username, String email, ROLES role) {
        this.username = username;
        this.email = email;
        this.role = role;
        this.profilePicture = null;
        this.friends = new ArrayList<>();
        this.usersBanned = new ArrayList<>();
        this.groups = new ArrayList<>();
        this.pages = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new User with the specified username, email, and profile picture.
     *
     * @param username The username of the user.
     * @param email The email address of the user.
     * @param profilePicture The profile picture of the user.
     */
    public User(String username, String email, Binary profilePicture) {
        this.username = username;
        this.email = email;
        this.role = ROLES.USER;
        this.profilePicture = profilePicture;
        this.friends = new ArrayList<>();
        this.usersBanned = new ArrayList<>();
        this.groups = new ArrayList<>();
        this.pages = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new User with the specified username, email, role, and profile picture.
     *
     * @param username The username of the user.
     * @param email The email address of the user.
     * @param role The role of the user.
     * @param profilePicture The profile picture of the user.
     */
    public User(String username, String email, ROLES role, Binary profilePicture) {
        this.username = username;
        this.email = email;
        this.role = role;
        this.profilePicture = profilePicture;
        this.friends = new ArrayList<>();
        this.usersBanned = new ArrayList<>();
        this.groups = new ArrayList<>();
        this.pages = new ArrayList<>();
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Gets the unique identifier of the user.
     *
     * @return The ObjectId of the user.
     */
    public ObjectId getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the user.
     *
     * @param id The ObjectId to set as the user's identifier.
     */
    public void setId(ObjectId id) {
        this.id = id;
    }

    /**
     * Gets the username of the user.
     *
     * @return The username.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the user.
     *
     * @param username The username to set.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the email address of the user.
     *
     * @return The email address.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the user.
     *
     * @param email The email address to set.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the role of the user.
     *
     * @return The role.
     */
    public ROLES getRole() {
        return role;
    }

    /**
     * Sets the role of the user.
     *
     * @param role The role to set.
     */
    public void setRole(ROLES role) {
        this.role = role;
    }

    /**
     * Gets the profile picture of the user.
     *
     * @return The profile picture as binary data.
     */
    public Binary getProfilePicture() {
        return profilePicture;
    }

    /**
     * Sets the profile picture of the user.
     *
     * @param profilePicture The profile picture to set.
     */
    public void setProfilePicture(Binary profilePicture) {
        this.profilePicture = profilePicture;
    }

    /**
     * Gets the list of friends of the user.
     *
     * @return The list of friends (ObjectIds).
     */
    public List<ObjectId> getFriends() {
        return friends;
    }

    /**
     * Sets the list of friends of the user.
     *
     * @param friends The list of friends to set.
     */
    public void setFriends(List<ObjectId> friends) {
        this.friends = friends;
    }

    /**
     * Gets the list of users banned by this user.
     *
     * @return The list of banned users (ObjectIds).
     */
    public List<ObjectId> getUsersBanned() {
        return usersBanned;
    }

    /**
     * Sets the list of users banned by this user.
     *
     * @param usersBanned The list of banned users to set.
     */
    public void setUsersBanned(List<ObjectId> usersBanned) {
        this.usersBanned = usersBanned;
    }

    /**
     * Gets the list of groups the user is part of.
     *
     * @return The list of groups (ObjectIds).
     */
    public List<ObjectId> getGroups() {
        return groups;
    }

    /**
     * Sets the list of groups the user is part of.
     *
     * @param groups The list of groups to set.
     */
    public void setGroups(List<ObjectId> groups) {
        this.groups = groups;
    }

    /**
     * Gets the list of pages the user is associated with.
     *
     * @return The list of pages (ObjectIds).
     */
    public List<ObjectId> getPages() {
        return pages;
    }

    /**
     * Sets the list of pages the user is associated with.
     *
     * @param pages The list of pages to set.
     */
    public void setPages(List<ObjectId> pages) {
        this.pages = pages;
    }

    /**
     * Gets the date and time when the user was created.
     *
     * @return The creation date and time of the user.
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the date and time when the user was created.
     *
     * @param createdAt The creation date and time to set.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
