spring.application.name=abyss-explore
spring.mongodb.uri=mongodb://localhost:27017/abyss-social
security.jwt.secret-key = lacleftressecretecomportantdeschiffresetdeslettresetdelongueur64
security.jwt.expiration-time = 3600000
recommendation.api.base-url=http://localhost:8000