spring.application.name=abyss-explore

# Authentification configuration
security.jwt.secret-key = lacleftressecretecomportantdeschiffresetdeslettresetdelongueur64
security.jwt.expiration-time = 3600000

# External API configuration
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/abyss-social}
recommendation.api.base-url=${RECOMMENDATION_API_BASE_URL:http://localhost:8000}
stable-diffusion.api.base-url = ${STABLE_DIFFUSION_API_BASE_URL:http://localhost:5005/api}
