package fr.univartois.butinfo.sae.abyss.social.mapper;

import fr.univartois.butinfo.sae.abyss.social.dto.UserDTO;
import fr.univartois.butinfo.sae.abyss.social.dto.UserResponseDTO;
import fr.univartois.butinfo.sae.abyss.social.model.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * Mapper interface for converting between User entities and UserDTOs.
 * This interface uses MapStruct to generate the implementation
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Converts a User entity to a UserDTO.
     * This method maps the fields of the User entity to the corresponding fields in the UserDTO, allowing for data transfer between layers of the application.
     * @param user The User entity to be converted to a UserDTO
     * @return A UserDTO object containing the data from the User entity, suitable for transfer between layers of the application
     */
    @Mapping(target = "password", ignore = true)
    UserDTO toDTO(User user);

    /**
     * Converts a UserDTO to a User entity.
     * @param userDTO The UserDTO to be converted to a User entity. This method maps the fields of the UserDTO to the corresponding fields in the User entity, while also setting default values for certain fields such as role, friends, usersBanned, groups, and createdAt.
     *                The id field is ignored during this mapping process, as it will be generated by MongoDB when the User entity is saved to the database.
     * @return A User entity containing the data from the UserDTO, with default values set for certain fields and the id field ignored, suitable for persistence in the MongoDB database
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "role", defaultValue = "USER")
    @Mapping(target = "friends", defaultExpression = "java(new java.util.ArrayList<>())")
    @Mapping(target = "usersBanned", defaultExpression = "java(new java.util.ArrayList<>())")
    @Mapping(target = "groups", defaultExpression = "java(new java.util.ArrayList<>())")
    @Mapping(target = "pages", defaultExpression = "java(new java.util.ArrayList<>())")
    @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
    User toEntity(UserDTO userDTO);

    /**
     * Converts a list of User entities to a list of UserDTOs. This method iterates over the list of User entities and converts each one to a UserDTO using the toDTO method, returning a list of UserDTOs that can be used for data transfer between layers of the application.
     * @param users The list of User entities to be converted to a list of UserDTOs. Each User entity in the list is processed and converted to a UserDTO using the toDTO method, resulting in a list of UserDTOs that can be used for data transfer between layers of the application.
     * @return A list of UserDTO objects containing the data from the list of User entities, suitable for transfer between layers of the application
     */
    List<UserDTO> toDTOList(List<User> users);

    /**
     * Converts a User entity to a UserResponseDTO. This method maps the fields of the User entity to the corresponding fields in the UserResponseDTO, allowing for data transfer between layers of the application while excluding sensitive information such as the password.
     * @param user The User entity to be converted to a UserResponseDTO. This method maps the fields of the User entity to the corresponding fields in the UserResponseDTO, while ignoring sensitive information such as the password, resulting in a UserResponseDTO that can be used for data transfer between layers of the application without exposing sensitive information.
     * @return A UserResponseDTO object containing the data from the User entity, suitable for transfer between layers of the application while excluding sensitive information such as the password
     */
    UserResponseDTO toResponseDTO(User user);
}

